### ISSUE TITLE
vue webpack build error with Error: getaddrinfo ENOENT

### ISSUE THREAD

**Issue by zhengoogle** [zhengoogle/Proj02-VueDebug#1]
Error: getaddrinfo ENOENT
    at Object._errnoException (util.js:1024:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)
npm ERR! code ELIFECYCLE

**Comment by zhengoogle** [comment]
resolved:
C:\Windows\System32\drivers\etc\hosts
comment
#0.0.0.0 localhost
